# NumPy arrays

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0,5,5) #print 5 evenly spaced number between 0 and 5 

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [15]:
np.eye(4) #to create an identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5) #to generate an 1-D array of 5 values uniformly distributed between 0 and 1

array([0.50513036, 0.31850246, 0.75617625, 0.97362833, 0.77749323])

In [17]:
np.random.rand(5,5) #to generate a 2-D array

array([[0.98644022, 0.20388864, 0.5277381 , 0.16996895, 0.30110466],
       [0.66138709, 0.47491255, 0.90674421, 0.28195882, 0.50733133],
       [0.6690738 , 0.34536415, 0.9393419 , 0.14984372, 0.44423206],
       [0.92713284, 0.61911298, 0.69754786, 0.75790494, 0.42029723],
       [0.08784   , 0.56995713, 0.71323315, 0.77718595, 0.63026634]])

In [18]:
np.random.randn(3) #creates an array of specified shape and fills it with random values as per standard normal distribution

array([ 2.16102793,  1.07676742, -0.95525281])

In [19]:
np.random.randn(3, 3)

array([[-0.10735834, -0.50427219,  1.2032048 ],
       [-0.08742938, -0.0772812 , -1.57445648],
       [ 1.10666621,  0.60109713,  2.62457109]])

In [20]:
np.random.randint(1,100,10)

array([24, 19, 48, 94, 72, 75, 96, 96, 69, 23])

In [21]:
np.random.randint(1,100)

75

In [22]:
arr = np.arange(25)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr = np.random.randint(0,25,10)

In [25]:
ranarr

array([14, 20, 18, 13, 24, 17,  5,  4,  6,  7])

In [26]:
arr.reshape(5,5) #reshape the 1-D array into a 2-D array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
ranarr.max()

24

In [28]:
ranarr.min()

4

In [29]:
ranarr.argmax()

4

In [30]:
ranarr.argmin()

7

In [31]:
arr.shape

(25,)

In [32]:
arr = arr.reshape(5,5)

In [33]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
arr.shape

(5, 5)

In [35]:
arr.dtype

dtype('int32')

In [36]:
from numpy.random import randint

In [37]:
randint(5)

2

In [38]:
arr2D = np.zeros((10,10))

In [39]:
arr2D

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
arr_length = arr2D.shape[1]

In [41]:
arr_length

10

In [43]:
for i in range(arr_length):
    arr2D[i] = i
arr2D

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [45]:
arr2D[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [46]:
arr2D[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [47]:
arr2D.shape


(10, 10)